language: java
jdk: oraclejdk8

install:
- mkdir -p $HOME/.gradle
- echo "gradle.publish.key=$GRADLE_PUBLISH_KEY" >> $HOME/.gradle/gradle.properties
- echo "gradle.publish.secret=$GRADLE_PUBLISH_SECRET" >> $HOME/.gradle/gradle.properties

script:
- ./gradlew check

after_success:
- test ${TRAVIS_TAG} && ./gradlew publishPlugins
